# Generated by Django 5.1.4 on 2024-12-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
